name: htracker
channels:
  - defaults
dependencies:
  - python==3.8.5
  - numpy==1.19.2
  - scipy==1.5.2
  - pandas==1.2.3
  - scikit-image==0.18.1
  - pylops==1.15.0
  - pyproximal==0.1.0
  - segyio==1.9.6 
  - matplotlib==3.4.2
  - jupyter==1.0.0

